apiVersion: apps/v1
kind: Deployment
metadata:
  name: gg-deployment
  labels:
    app: gg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gg
  template:
    metadata:
      labels:
        app: gg
    spec:
      containers:
      - name: gg
        image: 789921810407.dkr.ecr.ap-south-1.amazonaws.com/testing-boot8:2
        ports:
        - containerPort: 80
