apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    name: nodeapp
spec:
  containers: 
    - name: nodeapp
      image: 789921810407.dkr.ecr.ap-south-1.amazonaws.com/testing-boot8:2
      ports:
        containerPort: 8080
